### ISSUE TITLE
using netfs on a passwordless windows account

### ISSUE THREAD

**Issue by sdomino** [nanobox-io/nanobox#211]
when mount is set to netfs, nanobox is unable to detect a boxfile (works with native)

**Comment by lyondhill** [comment]
on retry does that problem go away? I have seen on all os's with netfs that on occasion the mounts dont show up as timely as they do using native so the boxfile detection hook doesnt have the mounts.

**Comment by yeapiekiyay** [comment]
I believe this is due to the fact that there's no password on my laptop. When it asks for me to enter my password when it's trying to mount the filesystem, I just hit the "enter" key because I have no password. Booted up on my desktop (Windows 10 as well) which has a password. Entered my password when mounting the fileshare and everything worked perfectly. Going to have to try throwing a password on my laptop and entering it to see if that fixes the issue.

**Comment by lyondhill** [comment]
Im going to try out a few things with a passwordless windows user today just to see if i can get the netfs mount to work without the password.

**Comment by lyondhill** [comment]
So in testing it turns out doing the network share without a password is not working for me. I even set the net share to be /GRANT:Everyone,FULL and was unable to attach to it with cifs.
