### ISSUE TITLE
If a folder has existing data docker doesnt mount on top of it

### ISSUE THREAD

**Issue by lyondhill** [nanobox-io/nanobox#237]

**Comment by tylerflint** [comment]
After further inspection this doesn't appear to be true. Still digging...

**Comment by Noah-Heil** [comment]
Yeah I don't know if there could be a little better description about what exactly is happening because unless you are mounting your volumes incorrectly I don't see what could be going on here...So you might be able to interpret this bug one of two ways...
first way: You want to mount a volume and have access to the data...this should work out of the box just by mounting it as a volume and you should be golden....unless you are using windows (so docker for windows...maybe even for mac b/c it still uses docker-machine) then you must make sure to be running your docker (instance/compose/whatever else) from the same account as the account that you used to share your local drive with your docker daemon so everything has to be running with the same account and privileges.
second way is that you want your volume to mount and while mounting overwrite the data that is already there...if you want that so bad why not just delete the data yourself...

**Comment by tylerflint** [comment]
@Noah-Heil Your insight into this is greatly appreciated. We're starting to think the scenario which lead us down this path was misunderstood, which it sounds like you would agree with. I think we'll probably close this issue in the coming days or perhaps change the topic once we get more information on a better direction.

Thanks!
