### ISSUE TITLE
Change linux netfs running message to be more descriptive

### ISSUE THREAD

**Issue by Max9403** [nanobox-io/nanobox#333]
The wording on the current error screen makes it look like a command line program is missing could the error message be reformatted to indicate that a service needs to be started?

Note sure if this should go into a different issue, but maybe give a suggestion for what command should be run to check that it's running, e.g. `sudo sytemctl start nfs-server`

**Comment by lyondhill** [comment]
can you link the message your talking about, I want to make sure we get the correct message

**Comment by Max9403** [comment]
```
Using nanobox with docker-machine requires tools that appear to not be available on your system.
netfs
View these requirements at docs.nanobox.io/install/requirements/docker-machine/
```

**Comment by lyondhill** [comment]
The messaging in this location is intended to point the user not to a solution but to the documentation where more details can be found.

Although the message from nanobox is intentionally vague i believe the contents of the link is sufficient to point people to take appropriate action.

If more could be done I would appreciate feedback.

**Comment by Max9403** [comment]
I'd agree about the link if it contained info for linux, though a vague error message is mostly useless to a user especially since that error message had me searching for a LONG time since it did not specify what part was wrong

**Comment by lyondhill** [comment]
The information at that link is specific about Linux

**Comment by Max9403** [comment]
>OSX 
>linux

**Comment by lyondhill** [comment]
@sanderson I believe it should be detecting your OS and taking you there automatically.

**Comment by sanderson** [comment]
Sorry, the page is supposed to auto-detect the OS and display the content accordingly. I tested on Linux, but it may not be detecting your specific distro correctly. I just updated the content in that doc a bit to clarify a bit of what is needed.

We don't provide specific installation/start/stop instructions for nfs because the methods vary widely between distros. It'd be a tall-order to document and maintain all of them.

*On a side note, using native docker on Linux is a lot faster than running docker-machine in VirtualBox*
