### ISSUE TITLE
brew-able install @ os x

### ISSUE THREAD

**Issue by minhoryang** [nanobox-io/nanobox#40]
If nanobox can be installed by [brew](http://brew.sh) or [brew-cask](http://caskroom.io/), then I'll really love it and spread more easily!
Thanks for reading this.

**Comment by sdomino** [comment]
@glinton we've had a few people bring this up, and I feel like it is a great idea. Once we get a chance, we'll have to look into it.

**Comment by adityadalal924** [comment]
Hi, I'm one of the maintainers of Homebrew Cask - I added a preliminary nanobox install last night (thanks to @liljenstolpe for suggesting the formula) and will add in the required dependencies later today, so you can do `brew cask install nanobox` and be ready to go

**Comment by adityadalal924** [comment]
Also, we do really like versioned installs as a general preference, any chance that's a possibility in the future?

**Comment by adityadalal924** [comment]
Done - https://github.com/caskroom/homebrew-cask/blob/master/Casks/nanobox.rb

You can now use `brew cask install nanobox`

**Comment by sanderson** [comment]
Thanks for this @adityadalal924! This is great. I've also noted your issue in the nanobox-installer project and will have @glinton, who maintains the installer, take a look.

**Comment by sanderson** [comment]
@adidalal - It's been a while since this issue was closed, but we have some really exciting news. We're getting ready to launch Nanobox into private beta and have completely rebuilt the Nanobox CLI. We're hoping you or someone more familiar with cask would be able to update the Nanobox cask. Here's what needs to be updated:

### New Executables
The new version of Nanobox requires two executables:

- `nanobox` - the nanobox cli
-  `nanobox-update` - the nanobox update manager

The current cask only installs the nanobox executables. Here are the locations of each:

nanobox: https://s3.amazonaws.com/tools.nanobox.io/nanobox/v1/darwin/amd64/nanobox
nanobox-update: https://s3.amazonaws.com/tools.nanobox.io/nanobox/v1/darwin/amd64/nanobox-update

### We No Longer Use Vagrant
Nanobox no longer relies on Vagrant, so the vagrant dependency can be removed from the cask.

Any help would be greatly appreciated. If you have any questions, feel free to let me know.

**Comment by adidalal** [comment]
Hey @sanderson, glad to see this project is alive and doing well!

We've also had some changes in the meantime, and cli-only tools that are open source are encouraged to make a Formula and be a part of `brew` itself. See https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook (Specifically, https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Acceptable-Formulae.md)

That being said, sometimes that's not the right home, and we're happy to continue having `nanobox` in Homebrew Cask.

Let me know which you prefer, and if it turns out to be the latter, I can help out with upgrading the Cask.

**Comment by sanderson** [comment]
Thanks for the info! Let me talk with the team and I'll get back to you.

**Comment by tylerflint** [comment]
@sanderson @adidalal If you're willing to do this for us that would be greatly appreciated!

**Comment by lyondhill** [comment]
This issue has been de-prioritized in favor of using the installers

**Comment by adidalal** [comment]
Should the cask be removed or pointed towards the .pkg installer?

**Comment by tylerflint** [comment]
Pointing to the installer would be awesome! Here is the new link: https://s3.amazonaws.com/tools.nanobox.io/installers/v1/mac/Nanobox.pkg

Thanks!

**Comment by adidalal** [comment]
Can I have the package name(s)? (For the uninstall stanza commands). Should be com.namobox.* Also if there are any directories that should be removed in addition. 

I'm assuming not but haven't actually used the app so a confirmation would be great.

**Comment by adidalal** [comment]
Just following up as I recently ran across the Cask again.


I saw 
```
io.nanobox.pkg.nanobox
org.virtualbox.pkg.vboxkexts
org.virtualbox.pkg.virtualbox
org.virtualbox.pkg.virtualboxcli
``

ie. `org.virtualbox.pkg.*`

Your `.pkg`'s Virtualbox is outdated and doesn't come with an uninstall, FYI.

Also, it seems that the instructions on the homepage are only for linux CLI install, not for OSX. (linux -> darwin in the URL)

**Comment by glinton** [comment]
As the CLI is no longer public, this issue is obsolete.
