### ISSUE TITLE
Fails to create /app/vendor mount

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#426]
Something seems amiss with `nanobox run` when executed on a Linux (Debian) host with Docker native:

```
$ nanobox version
Nanobox version 2.0.4 (5d0aadd123e877eafe5cd122b081575f)

$ nanobox run 
Preparing environment :

--------------------------------------------------------------------------------
+ HEADS UP:
+ This is the first build for this project and will take longer than usual.
+ Future builds will pull from the cache and will be much faster.
--------------------------------------------------------------------------------


Building runtime :
  ✓ Starting docker container
  ✓ Preparing environment for build
  ✓ Gathering requirements
  ! Mounting cache_dirs

! FAILED TO MKDIR -P /APP//VENDOR !

Exit
 1

Command
 su - gonano -c "mkdir -p /app//vendor"

Output
 mkdir: cannot create directory ‘/app//vendor’: Permission denied


Error   : failed to execute hook (mount) on 950cc75d98083b67230b6d505d54345c4b6b029afd021566b70fc48b2cb15413: util:Exec:/opt/nanobox/hooks/mount: bad exit code(1): 
Context : failed to build the code
```

Due to the error itself I cannot enter the container and check the permissions. Any idea?

**Comment by lyondhill** [comment]
Interesting the mkdir is happening on the container. I thin @notxarb  might be able to shed some more  light on this. also it appears /app//vendor is trying to be created. Im assuming its because some variable is missing between /app/ and /vendor

**Comment by glinton** [comment]
So far, the only way I've been able to reproduce this is if I have the code in my current directory owned by root. I believe the reason this isn't an issue with virtualbox is because the code is mounted as the gonano user.

Possible solutions: 
* `chown` the code (not a great idea as it would modify it locally for the user)
* bind mount the code to another location as user/group 1000 so the hooks work

Potential workarounds for users:
* manually create directories as they are needed, and ensure they are writable by all
* `chown` the code as user 1000 (`chown -R 1000:1000 .` from app directory)

*Note: This will likely also be an issue if the code owner's id is not 1000*

**Comment by glinton** [comment]
Stems from docker's inability to set owner/group of mounted volumes ([this issue](https://github.com/moby/moby/issues/2259))

**Comment by glinton** [comment]
@mbrodala @rkkautsar and anyone else affected. I have created a test build image that should resolve this issue which I will redefine in a moment.  To test, ensure you have the following in your boxfile:

```yaml
run.config:
  image: nanobox/build:bugfix_user
```
I still don't suggest running nanobox as root, but I believe this should even work if you still choose to do so (only tested one time as root).

The issue is bind mounting, and the fact that docker uses it. Bind mounts themselves are fantastic, but have limitations; such as the inability to set the owner/group. Since nanobox with docker native uses docker volumes (bind mounts) to your code, whoever owns them on your laptop will own them inside the container. Nanobox has created a user to run user applications and hooks, the user id of this user is 1000.

With default file permissions, users cannot write to something they do not own. Hence the `Permission denied` errors. This fix makes our nanobox user pretend to be you, so you can go ahead and use nanobox without worrying about what user you are logged into.

**Comment by mbrodala** [comment]
I don't see the issue ATM with Nanobox version 2.1.0 (5d0aadd123e877eafe5cd122b081575f) ...

**Comment by glinton** [comment]
@hyusetiawan I'd suggest reaching out to us in [slack](https://nanoboxio.slack.com/messages) or opening a ticket. I believe yours is not this issue though it may have the same symptoms.

**Comment by hyusetiawan** [comment]
I solved it, kind of janky but it works. Turns out I had this solution for 2 of my deployments already
