### ISSUE TITLE
Linux version of Nanobox doesn't work under WSL

### ISSUE THREAD

**Issue by kristoftorfs** [nanobox-io/nanobox#461]
# Steps followed
1. Install VirtualBox under Windows
2. Make VBoxManage.exe available under WSL: `sudo ln -s /mnt/c/Program\ Files/Oracle/VirtualBox/VBoxManage.exe /usr/bin/VBoxManage`
3. Install NFS server under WSL: `sudo apt install nfs-kernel-server`

# Output
```
kristof@DESKTOP-BVK6V55:~$ nanobox
Using nanobox with docker-machine requires tools that appear to not be available on your system.
netfs
View these requirements at docs.nanobox.io/install/requirements/docker-machine/
```

**Comment by danhunsaker** [comment]
Looks like it's configured to use Docker instead of VirtualBox. Just as a side note.

As to NFS, the package you grabbed was the kernel package - there's no Linux kernel running on a Windows system, so that version can't work. I don't remember whether or not there's an NFS package that doesn't rely on kernel support, but you'd have to use it, if so.

**Comment by lyondhill** [comment]
@kristoftorfs I would assume we wont be able to do nfs using linux sub system for windows. I wonder if we would be able to run nanobox in this context using docker native, if when using docker-machine we would just have to use native mounting.

**Comment by kristoftorfs** [comment]
Well, I actually just moved from docker native to VirtualBox as I was unable to get it working at all (under Windows).

**Comment by lyondhill** [comment]
We intend to support windows subsystem for linux but we currently don't. Once WSL comes out of beta we will put the time and work into making both the windows version and the linux versions work in the context of WSL. Thanks for your patience.
