### ISSUE TITLE
question: Desktops inside virtualbox

### ISSUE THREAD

**Issue by joeblew99** [nanobox-io/nanobox#482]
Since this uses virtualBox, can i also launch desktops like Windows and OSX ?

I ask this because sure i need to model servers, but i also build GUI's for all Desktops and Mobiles and so off that i have to use vagrant & virtual box currently.

**Comment by danhunsaker** [comment]
Not with Nanobox, no. The actual technology under the hood, so to speak, is Docker; Nanobox just uses VirtualBox to get a Linux VM running so it can launch Docker containers inside it. Since Nanobox is designed for developing web applications, you'll only really gain any value from using it for the web side of your projects — web site, REST API, etc.

That said, Vagrant VMs should be able to connect to your Nanobox containers just as easily as anything else on your system can. So you should be able to test the web side of your projects that way.

**Comment by joeblew99** [comment]
thanks - not for me...
