### ISSUE TITLE
Add a config option to enable verbose rsync output

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#490]
From [this issue](https://github.com/nanobox-io/nanobox-docker-build/issues/128), if CI mode is set to true, nanobox should set the variable inside the build container `QUIET_SYNC` to `true`, if the (newly proposed) nanobox config option `ci-sync-verbose` is set to `true`, nanobox should set `QUIET_SYNC=false`.

`ci-sync-verbose` will need to be added as a nanobox config option.

**Comment by glinton** [comment]
From what I can tell, we'll likely want to throw something like this in the `deploy` somewhere, if you can think of a better way (passing in as a payload to the hook) let me know and we'll do that

```go
import (
	"github.com/nanobox-io/nanobox/helpers"
	"github.com/nanobox-io/nanobox/models"
	app_evar "github.com/nanobox-io/nanobox/processors/app/evar"
	"github.com/nanobox-io/nanobox/util/config"
)

func syncVerbosity() {
	_, _, name := helpers.Endpoint(env, args, 0)
	app, _ := models.FindAppBySlug(config.EnvID(), name)
	env, _ := models.FindEnvByID(config.EnvID())
	nanoConfig, _ := models.LoadConfig()
	if nanoConfig.CIMode {
		app_evar.Add(env, app, map[string]string{"QUIET_SYNC":"true"})
	}
	if nanoConfig.CISyncVerbose {
		app_evar.Add(env, app, map[string]string{"QUIET_SYNC":"false"})
	}
}
```

**Comment by lyondhill** [comment]
This isnt a bad idea. with variables that are based on a config I dont like setting them twice. I would suggest that instead of adding the evar to the app we would just set the evar during the appropriate hooks. This is good at avoiding the dispairity between config and app info. Users also have the ability to remove evars from an app, which could cause a unexpected response
