### ISSUE TITLE
Debian Package Installer has permissions error message on install

### ISSUE THREAD

**Issue by audieleon** [nanobox-io/nanobox#56]
Downloaded the .deb install package and tried to install by just double clicking on a fresh install of Ubuntu 15.10. 

I got this error message during install:

><b>The package is of bad quality</b>
>The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

>Details:
>Lintian check results for /home/audieleon/Downloads/nanobox-bundle.deb:
E: nanobox-bundle: control-file-has-bad-permissions postinst 0775 != 0755
E: nanobox-bundle: control-file-has-bad-permissions prerm 0775 != 0755

**Comment by sanderson** [comment]
Thanks for reporting @audieleon. I've assigned this issue to @glinton. He manages the installers.

**Comment by glinton** [comment]
@audieleon I just uploaded a new installer that should work for you.  I noticed you are installing the bundled version, since you are running 15.10, you should unselect the "include vagrant & virtual box"    
![image](https://cloud.githubusercontent.com/assets/2653109/11276560/c545a54e-8e9f-11e5-8389-bcb9567fa4ff.png)     
checkbox as the included virtualbox is the 14.04-15.04 version.

**Comment by audieleon** [comment]
Not sure if this should reopen this issue or not. Downloaded the new version with your fix, and I didn't get the same error. Thanks for getting to that so quickly.

Now I get a new error. This error is with the bundled installer which you advised against, and also with the version I get when I uncheck the box as suggested: The new error is 
>The package doesn't provide a valid Installed-Size control field. See Debian Policy 5.6.20.
