### ISSUE TITLE
failed to setup the network bridge -> failed to run configure hook

### ISSUE THREAD

**Issue by hl** [nanobox-io/nanobox#639]
I seem to have a strange problem when installing Nanobox on a new machine.

Only the first start fails, after a retry it all works. 

```
henricus@Workbook.local:/Users/henricus  $ n start
Root privileges are required to start the server. Your system password may be requested...
Starting Nanobox :
  ✓ Setting up custom docker network...
  ✓ Joining virtual network

Building bridge :
  ✓ Pulling nanobox/bridge image
  ✓ Starting docker container
  ! Setting up container
    /opt/gonano/hookit/lib/hookit/hook.rb:91:in `method_missing': undefined method `captures' for nil:NilClass (NoMethodError)
    	from /opt/nanobox/hooks/configure:34:in `<main>'

Error   : failed to execute hook (configure) on f4083725bad38880361b9ddf537970bbb434af57d343c63ce252b9247d92ae12: util:Exec:/opt/nanobox/hooks/configure: bad exit code(1):
Context : failed to setup the network bridge -> failed to run configure hook

henricus@Workbook.local:/Users/henricus  $ n start
✓ Skipping (already running)
Building bridge :
  ✓ Configuring
henricus@Workbook.local:/Users/henricus  $ n stop
Stopping Nanobox :
Root privileges are required to stop the server. Your system password may be requested...
henricus@Workbook.local:/Users/henricus  $ n start
Root privileges are required to start the server. Your system password may be requested...
✓ Skipping (already running)
Building bridge :
  ✓ Configuring
henricus@Workbook.local:/Users/henricus  $ n version
Nanobox Version 2.3.0-171214T1632 (6239a4e)
henricus@Workbook.local:/Users/henricus  $ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
henricus@Workbook.local:/Users/henricus  $
```

aside from that, the `implode` flag gives the following error

```
henricus@Workbook.local:/Users/henricus  $ n implode -v
Imploding Nanobox :
  Removing custom docker network... :

Error   : exit status 1
Context : failed to destroy the provider -> failed to destroy the provider

henricus@Workbook.local:/Users/henricus  $
```

**Comment by Shigawire** [comment]
I think I've tracked this down.
It looks like this command fails: https://github.com/nanobox-io/nanobox-hooks-bridge/blob/809b22637655d5cb2373eba64becae89167b5ecb/src/configure#L33

All images are based on `nanobox/runit`, which is based on `nanobox/base`. When I run `docker run --rm -it --network=nanobox nanobox/base /bin/bash` and then, inside the shell execute `ip addr show eth0`,  I get the following result:
```
29: eth0@if30: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:14:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.20.0.2/16 brd 172.20.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

The original regex (`\s+inet ([0-9.].+)\/([0-9]+) scope`) does not match, because the command also returns the broadcast IP set on the interface.
Updating the regex to `\s+inet ([0-9.].+)\/([0-9]+) (scope|brd)` works, though. (https://regex101.com/r/aRX9J8/1). However, I do not know where the problem comes from.

2 Options:
1. `nanobox/base` is based on docker's `ubuntu`-image. This image is not pinned to a particular version (https://github.com/nanobox-io/nanobox-docker-base/blob/master/Dockerfile), and there exists the chance that the underlying ubuntu image introduced breaking changes to the `ip  addr show` command.
2. Our docker networking setup is messed up and the `nanobox`-bridge is doing weird, unexpected things.

**Comment by Shigawire** [comment]
I "fixed" it by using the "lightweight VM"-option, i.e. nanobox running docker inside VirtualBox.

**Comment by valentinvucea** [comment]
Hmmm... that's a big change for me... I have also some containers using Docker native... so turn off Hyper-V and do everything in VirtualBox...

**Comment by Shigawire** [comment]
Well, I am not a developer of nanobox. But as this is FOSS, feel free to investigate and collect more evidence where the bug is coming from. If it is not the `ubuntu` base image it could be the nanobox/docker setup. Did you re-install something? Was it a fresh install?

I recall I downloaded the VirtualBox-version first but configured the CLI to run with docker native. No idea if the install packages contain different nanobox runtimes, but that could have broken something on my mac.

**Comment by Shigawire** [comment]
Then I suspect that this issue is catching more and more people over time who either reinstall or update the nanobox packages. But It could also be docker itself, supplying broadcast addresses to the containers in custom networks. But Google didn't turn anything up on that matter.

**Comment by valentinvucea** [comment]
I suspect Docker is the culprit. I found some earlier builds for Docker and Nanobox... installed them and... voila... it works... for now, this is my "fix".

**Comment by valentinvucea** [comment]
I'm sorry... I didn't see your reply... I narrowed down the problem to Docker.
See here:
https://docs.docker.com/docker-for-windows/release-notes/
Look for the last build from 2017... everything from 2018 throws the same error... probably since they started to have the "VM entirely built with Linuxkit"

**Comment by notxarb** [comment]
This has been fixed.
How to get the fix?
You'll need to make sure nanobox isn't running, pull the new docker image, destroy the bad container, and then you can start nanobox again:

nanobox stop
docker pull nanobox/bridge
docker stop nanobox_bridge
docker rm nanobox_bridge
nanobox start
