### ISSUE TITLE
Failed to validate provider - missing docker - exit status 1

### ISSUE THREAD

**Issue by pablorsk** [nanobox-io/nanobox#649]
I'm using nanobox on Ubuntu 16.04. And I'd like to use it with "Via Docker Native", but I receive an error message. (with VM works fine).

I run

```bash
$ nanobox start
Failed to validate provider - missing docker - exit status 1
Using nanobox with native requires tools that appear to not be available on your system.
docker
View these requirements at docs.nanobox.io/install
$ sudo nanobox start
Failed to validate provider - missing docker - exit status 1
Using nanobox with native requires tools that appear to not be available on your system.
docker
View these requirements at docs.nanobox.io/install
$ docker -v
Docker version 17.05.0-ce, build 89658be
``` 
Any ideas?

**Comment by pablorsk** [comment]
problem solved! :paintbrush: 

```bash
sudo usermod -aG docker $USER
# Log out and log back :)
```

**Comment by danhunsaker** [comment]
Try `docker ps` to ensure you can see containers on your system. If you can't, it will complain about permissions. The fix is to ensure your user account is in the `docker` group, and that you've logged out and back in to make the system update its records properly.

We don't support running Nanobox with `sudo`, by the way, as it generally causes more problems than it's worth, so try to avoid doing that, if possible.
