### ISSUE TITLE
Nanobox will not accept user password to mount onto Virtualbox

### ISSUE THREAD

**Issue by Jarmahent** [nanobox-io/nanobox#663]
`Kevin's(me) password is required to mount a Windows share. (must be your Windows Live password if linked)
Windows Password:`

I then put the correct password. Multiple times and it always says `[1A[K[1A[K  \ Mounting codebase :` Then proceeds to ask me again.

**Comment by Jarmahent** [comment]
Fixed, running: `nanobox config set mount-type native` made nanobox not ask me for password anymore

**Comment by raulingg** [comment]
Working. Thanks

**Comment by danhunsaker** [comment]
As a side note, this is a _workaround_ rather than a _fix_. The `native` `mount-type` is slower than the `netfs` `mount-type`, usually noticeably, so it has some tradeoffs.

The correct fix involves ensuring a few things are properly set up on your development system. First, you must use a password to log in to your computer - this is just good security practice anyway, but is also required by Windows to allow access to file shares on the host. Second, you need to mark the network used by the Nanobox network bridge (a TUN/TAP Adapter) as a Private network, so that Windows File Sharing will allow the Nanobox VM to actually see your shares. Then, you also need to ensure that file sharing is actually enabled at all, which can be a relatively involved process better explained by tutorials already elsewhere on the Internet. If all of these is currently set up correctly, then there's another problem somewhere that we'd have to collaboratively track down.

**Comment by rflash95** [comment]
I found a solution. You must allow file and printer sharing and file and printer sharing over SMBDirect on the private network.
![nanoboxo](https://user-images.githubusercontent.com/12154891/44572754-092f2480-a7af-11e8-9488-dfccea245098.png)

If the TAP adapter is still a public network because of an unidentified network, you can change it to the Local Security Policy -> Network List Manager Policies -> unidentified network -> Location Type -> select Private.
![local security policy](https://user-images.githubusercontent.com/12154891/44572804-37146900-a7af-11e8-9ad1-b72e3b26b0f3.png)

![private network](https://user-images.githubusercontent.com/12154891/44572945-80fd4f00-a7af-11e8-9ec0-718d85451f2e.png)

**Comment by Jarmahent** [comment]
@danhunsaker  Regardless, this needs to be fixed. I am 100% sure that the password I am using is correct and it still asks me for my password no matter what. It says I have to use my live account password if my windows machine is linked(which it is). I go and change it to a specific password, restart my computer and try running with mount type ntfs and it still does not let me.
