### ISSUE TITLE
http: proxy error: context canceled

### ISSUE THREAD

**Issue by smuemd** [nanobox-io/nanobox#667]
Hello,

I am getting this in the logs for a server on digital ocean.
![image](https://user-images.githubusercontent.com/3016582/41102636-a3eafb32-6a67-11e8-9a8b-420ddcd0bb1a.png)

the app itself runs fine.
What does this type logentry mean?

**Comment by tojacob** [comment]
Did you solve it?

**Comment by danhunsaker** [comment]
It's harmless, if a little annoying. Just means a broken client disconnected before the load balancer could send a response. Generally these are just bots scanning known cloud hosting ports for vulnerabilities - which they won't find - rather than legitimate users, since even old browsers will stick around to see the response.

**Comment by tojacob** [comment]
@danhunsaker Thanks for the info.
